// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicheWebErpAPI;

#nullable disable

namespace NicheWebErpAPI.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260719145919_AddCompanyLocationMapping")]
    partial class AddCompanyLocationMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NicheWebErpAPI.Models.Category", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeftTag")
                        .HasColumnType("int");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RightTag")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebPageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.CompanyLocation", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdministrationLeftTag")
                        .HasColumnType("int");

                    b.Property<Guid>("AdministrationParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdministrationRightTag")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("CompanyLocation", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ErpRole", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LegacyPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LegacyPersonId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ErpUser", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Label", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebPageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Label", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Product", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SizewayItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StyleColorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StyleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ProductLocation", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Allocated")
                        .HasColumnType("int");

                    b.Property<int>("AvailableFirm1")
                        .HasColumnType("int");

                    b.Property<int>("AvailablePerson1")
                        .HasColumnType("int");

                    b.Property<int>("Held")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PurchaseOrder")
                        .HasColumnType("int");

                    b.Property<int>("RentalHeld")
                        .HasColumnType("int");

                    b.Property<int>("RentalOrder")
                        .HasColumnType("int");

                    b.Property<int>("RentalOut")
                        .HasColumnType("int");

                    b.Property<int>("RequiredOut")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderFirm")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderPerson")
                        .HasColumnType("int");

                    b.Property<Guid?>("StyleSellLocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransitIn")
                        .HasColumnType("int");

                    b.Property<int>("TransitOut")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("ProductLocation", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Style", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowManualDescription")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowManualPrice")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoPopUp")
                        .HasColumnType("bit");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LabelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonStock")
                        .HasColumnType("bit");

                    b.Property<Guid>("RangeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SizewayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortRankMajor")
                        .HasColumnType("int");

                    b.Property<int>("SortRankMinor")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WebMainPictureID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Style", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpUser", b =>
                {
                    b.HasOne("NicheWebErpAPI.Models.ErpRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NicheWebErpAPI.Models.ErpUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
