// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicheWebErpAPI;

#nullable disable

namespace NicheWebErpAPI.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    partial class ERPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NicheWebErpAPI.Models.Category", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeftTag")
                        .HasColumnType("int");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RightTag")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebPageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Category", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.CompanyLocation", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdministrationLeftTag")
                        .HasColumnType("int");

                    b.Property<Guid>("AdministrationParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdministrationRightTag")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultPricePointRRPID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultPricePointRetailID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultPricePointWebID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultPricePointWholesaleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultTaxJurisdictionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FreightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GeneralEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumLicenses")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("CompanyLocation", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ErpRole", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LegacyPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LegacyPersonId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ErpUser", (string)null);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Firm", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowOrder")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DenyLabelsByDefault")
                        .HasColumnType("bit");

                    b.Property<decimal>("DepositPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MainContactID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ParentFirmID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PricePointID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TermsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Firm", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Label", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebPageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Label", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Person", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AllowCredit")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DefaultIdentityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonNo"));

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Person", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.PricePoint", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefaultInternationalSalesRevenueGeneralLedgerAccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefaultInternationalTaxJurisdictionCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefaultLocalSalesRevenueGeneralLedgerAccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefaultLocalTaxJurisdictionCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TaxInclusive")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaxJurisdictionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("PricePoint", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Product", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SizewayItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StyleColorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StyleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Product", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ProductLocation", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Allocated")
                        .HasColumnType("int");

                    b.Property<int>("AvailableFirm1")
                        .HasColumnType("int");

                    b.Property<int>("AvailablePerson1")
                        .HasColumnType("int");

                    b.Property<int>("Held")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PurchaseOrder")
                        .HasColumnType("int");

                    b.Property<int>("RentalHeld")
                        .HasColumnType("int");

                    b.Property<int>("RentalOrder")
                        .HasColumnType("int");

                    b.Property<int>("RentalOut")
                        .HasColumnType("int");

                    b.Property<int>("RequiredOut")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderFirm")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderPerson")
                        .HasColumnType("int");

                    b.Property<Guid?>("StyleSellLocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransitIn")
                        .HasColumnType("int");

                    b.Property<int>("TransitOut")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("ProductLocation", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Range", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentRangeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebPageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Range", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Season", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IndentEarliestDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IndentLatestDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Season", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Size", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Size", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Sizeway", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExcludeRetailSearch")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Sizeway", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.SizewayItem", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("SizeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SizewayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("SizewayItem", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.Style", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowManualDescription")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowManualPrice")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoPopUp")
                        .HasColumnType("bit");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LabelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetaTagDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTagTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonStock")
                        .HasColumnType("bit");

                    b.Property<Guid>("RangeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SizewayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortRankMajor")
                        .HasColumnType("int");

                    b.Property<int>("SortRankMinor")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WebMainPictureID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("Style", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.StyleColor", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasSwatchImage")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSwatchThumbnail")
                        .HasColumnType("bit");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RgbValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StyleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("StyleColor", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.StylePrice", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InternationalSalesRevenueGeneralLedgerAccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InternationalTaxJurisdictionCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InternationalUnitPriceExTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InternationalUnitPriceTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LocalSalesRevenueGeneralLedgerAccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocalTaxJurisdictionCategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LocalUnitPriceExTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LocalUnitPriceTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PricePointID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StyleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("StylePrice", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.StyleSellLocation", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AllowRental")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AllowRetail")
                        .HasColumnType("tinyint");

                    b.Property<bool>("AllowRetailLayBy")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowRetailPreorder")
                        .HasColumnType("bit");

                    b.Property<byte>("AllowWebRetail")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AllowWebRetailCatalogue")
                        .HasColumnType("tinyint");

                    b.Property<bool>("AllowWebRetailLayBy")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWebRetailPreOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWebRetailStock")
                        .HasColumnType("bit");

                    b.Property<byte>("AllowWebWholesaleIndent")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AllowWebWholesaleStock")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AllowWholesaleIndent")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PricePointRRPID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PricePointRetailID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PricePointWebID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StyleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("StyleSellLocation", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.TradingTerms", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaysFrom1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<decimal>("SettlementDiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("TradingTerms", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.TransactionBase", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CurrencyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerReferenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentNumber1")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<Guid>("LaneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumLines1")
                        .HasColumnType("int");

                    b.Property<Guid>("OtherPartyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PricePointID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepresentativeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status1")
                        .HasColumnType("int");

                    b.Property<int?>("Status2")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotalStyles1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotalStylesTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TermsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalQuantities1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("TransactionBase", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.TransactionLine", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LineAmountExTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LineQuantity1")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTaxAmount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PricePointID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<decimal?>("StylePriceExTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StylePriceTax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("StyleSellLocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("TransactionLine", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.TransactionQuantity", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Allocated")
                        .HasColumnType("int");

                    b.Property<string>("EntityClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Held")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductLocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RequiredOut")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderFirm")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderPerson")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionLineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedByID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyID", "EntityID");

                    b.ToTable("TransactionQuantity", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpUser", b =>
                {
                    b.HasOne("NicheWebErpAPI.Models.ErpRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NicheWebErpAPI.Models.ErpUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NicheWebErpAPI.Models.ErpRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
